name: Docker Image

on:
  push:
    branches: [ "master" ]
    tags:
      - v*
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Metadata action
      uses: docker/metadata-action@v5.5.1
      with:
        images: gyrogearl00se/solace-web-client
        tags: |
          type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'master') }}
          type=ref,event=tag
          
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        push: ${{ GitHub.event_name != 'pull_request' || contains(GitHub.head_ref, 'feature') }}
        tags: ${{ steps.meta.outputs.tags }}
